### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by nxuv** [al1-ce/sily-raylib#1]
- [ ] Wrap raylib
- [ ] Add custom resources
- [ ] Add Newton Dynamics support
- [ ] Add gameobject component system
- [ ] Add editors
- [ ] Test for needed changes
- [ ] Make test game
- [ ] PBR
- [x] Fork into ?gamelib?
- [ ] Add OpenGL wrapper
- [ ] Replace all OpenGL calls
- [ ] Add SDL wrapper
- [ ] Replace all GLFW calls
- [ ] ...?
- [ ] Test for needed changes
- [ ] Integrate audio engine (possibly SoLoud)
- [ ] Deferred rendering
- [ ] Make test game
- [ ] Custom game engine (working name RayLight)
